### ISSUE TITLE
Support float -> double casting in function calls

### ISSUE THREAD

**Issue by underwoo16** [sjbarag/brs#384]
Reference implementation supports passing a `float` into functions that specifies a parameter of type `double`. 

Consider the following example:

```brightscript
sub main()
    print "main.brs start"
    func1(100)
    print "main.brs end"
end sub

sub func1(position as integer)
    print "in func 1"
    print position
    func2(position)
end sub

sub func2(position as float)
    print "in func 2"
    print position
    func3(position)
end sub

sub func3(position as double)
    print "in func 3"
    print position
end sub
```

This executes successfully until `func3`is called, at which point it throws the following error:

```
./integer-float-double.brs(16,18-19): Provided arguments don't match func3's signature.
    function func3(position as Double) as Void:
        * Argument 'position' must be of type Double, but received Float.Runtime error encountered in BRS implementation:  Error: Something terrible happened and we didn't throw a `BlockEnd` instance.
    at Interpreter.visitCall (/usr/local/lib/node_modules/brs/lib/interpreter/index.js:812:27)
    at Call.accept (/usr/local/lib/node_modules/brs/lib/parser/Expression.js:28:24)
    at Interpreter.evaluate (/usr/local/lib/node_modules/brs/lib/interpreter/index.js:1226:27)
    at Interpreter.visitExpression (/usr/local/lib/node_modules/brs/lib/interpreter/index.js:255:21)
    at Expression.accept (/usr/local/lib/node_modules/brs/lib/parser/Statement.js:41:24)
    at Interpreter.execute (/usr/local/lib/node_modules/brs/lib/interpreter/index.js:1229:26)
    at block.statements.forEach.statement (/usr/local/lib/node_modules/brs/lib/interpreter/index.js:756:52)
    at Array.forEach (<anonymous>)
    at Interpreter.visitBlock (/usr/local/lib/node_modules/brs/lib/interpreter/index.js:756:26)
    at Block.accept (/usr/local/lib/node_modules/brs/lib/parser/Statement.js:32:24)
```

**Comment by strattonbrazil** [comment]
Looking at the implementation it's actually casting these values so passing a float to a double type, for example, will change it to a double. Similarly, passing a float to an int type will cast it to an int.

**Comment by strattonbrazil** [comment]
When we're about to raise this error, we might want to try casting it to the desired type first to see if that's successful.  I don't know how to map a ValueKind to a constructor though.  
```
if (
    returnedValue &&
    satisfiedSignature.signature.returns !== ValueKind.Dynamic &&
    satisfiedSignature.signature.returns !== returnedValue.kind
) {
    // try casting it to the type first
    try {

    } catch {
        this.addError(
            new Stmt.Runtime(
                `Attempting to return value of type ${ValueKind.toString(
                    returnedValue.kind
                )}, ` +
                    `but function ${callee.getName()} declares return value of type ` +
                    ValueKind.toString(satisfiedSignature.signature.returns),
                returnLocation
            )
        );    
    }
}
```

**Comment by sjbarag** [comment]
As you called out in #385 , this is pretty similar to #360 and likely needs a special-case.  There's no way to directly map a `ValueKind` to a constructor other than via `switch` statement — luckily the mapping is very simple.

I got really close to consolidating all the call-time type corrections into `Callable.ts` in https://github.com/sjbarag/brs/tree/unbox-objects-for-primitive-params-and-returns but had to drop it for some reason that I now can't remember.  That'll take care of #369 and make fixing this (and #385) much simpler.
