### ISSUE TITLE
MacOS: `brs` crashes on launch

### ISSUE THREAD

**Issue by sjbarag** [sjbarag/brs#55]
Stack trace:

```
$ brs
module.js:549
    throw err;
    ^

Error: Cannot find module 'node-int64'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ($HOME/.local/lib/node_modules/brs/lib/lexer.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Repro steps: `yarn global add brs && brs`

Versions:
* `node`: 8.11.2
* `yarn`: 1.6.0
* Mac OS X: 10.12.6

**Comment by sjbarag** [comment]
Can't repro after a remove/reinstall.
